name: CI

on: push

jobs:
  build:
    # on is a trigger
    runs-on: ubuntu-latest

    # commands to run
    steps:
      - name: QA Test
        uses: actions/checkout@v2

      - name: Install
        # gets run in the shell
        run: npm install
        
      - name: Lint
        run: npm run lint

      - name: Compile
        run: npm run compile

      - name: Test
        run: npm test